# Spring
spring:
  application:
    # 应用名称
    name: hugo-gateway


--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: 111.230.198.245:8848
      discovery:
        server-addr: 111.230.198.245:8848
        # 注册组
        group: public
        namespace: public
      config:
        server-addr: 111.230.198.245:8848
        # 配置
      password: nacos
      username: nacos
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml
